### ISSUE TITLE
Why all the objc_runtime stuff?

### ISSUE THREAD

**Issue by harlanhaskins** [michaeljbishop/NGAParallaxMotion#8]
Can't all of that be done much more cleanly with properties inside class extensions or instance variables?

**Comment by michaeljbishop** [comment]
I could be wrong here but my reading of [the documentation](https://developer.apple.com/library/ios/documentation/cocoa/conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html) implies:
1. Categories can't have ivars
2. Class extensions can, but you can only make a class extension on a class for which you are compiling the source code.

Because of this, I have to use the objc runtime to allocate storage to back the property.
